# Site settings
title: Bruno Vecchi
email: vecchi.b@gmail.com
description: "I write software for a living."
baseurl: ""
url: "http://brunov.org"

# Build settings
markdown: kramdown
permalink: pretty

username: brunoV
mastodon_username: brunov
