# Site settings
title: Bruno Vecchi
email: vecchi.b@gmail.com
description: "I write software for a living. It's a real job mom, I swear."
baseurl: ""
url: "http://brunov.org"

# Build settings
markdown: kramdown
permalink: pretty

username: brunoV
twitter_username: brunovi
